services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Monkey1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: