@host = http://localhost:5000/api

POST {{host}}/ITodosApi/addTodo
Content-Type: application/json
Accept: application/json

[{
    "Id": "de42ed3d-3fda-4403-888e-60aa39940b43",
    "Description": "add",
    "Created": "2023-01-24T13:25:16.159Z",
    "Completed": false,
    "Deleted": false
}]

###

GET {{host}}/ITodosApi/getTodos
Content-Type: application/json
Accept: application/json

###

GET {{host}}/ITodosApi/getTodo/1
Content-Type: application/json
Accept: application/json

###

GET {{host}}/ITodosApi/completeTodo
Content-Type: application/json
Accept: application/json

###